version: '3.8'
services:
   r_forest_training:
       build: .
       command: bash -c "python src/trainer.py --test_preds_out=data/preds.csv --model_save_path=data/r_forest.pickle && python src/predict.py && coverage run src/unit_tests/test_preprocess.py && coverage run -a src/unit_tests/test_training.py && coverage report -m"
       ports:
           - 8000:8000
       image: olegggatttor/ml-pipe-bike-sharing-with-db:latest
       links:
           - "mysql:mldb"
   mysql:
       ports:
           - ${MYSQL_CLIENT_PORT}:3306 # default mysql port for internal
       command: --init-file /data/application/init_ml_db.sql
       volumes:
           - ./init_ml_db.sql:/data/application/init_ml_db.sql
       container_name: mldb
       restart: unless-stopped
       environment:
           MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
           MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
           MYSQL_DATABASE: ml_pipe_db
       image: mysql