version: '3.8'
services:
   r_forest_training:
       build: .
       command: bash -c "python src/trainer.py --test_preds_out=data/preds.csv --model_save_path=data/r_forest.pickle && python src/predict.py --user=${MYSQL_ROOT_USER} --password=${MYSQL_ROOT_PASSWORD} --port=${MYSQL_CLIENT_PORT} && coverage run src/unit_tests/test_preprocess.py && coverage run -a src/unit_tests/test_training.py && coverage report -m"
       ports:
           - 8000:8000
       image: olegggatttor/ml-pipe-bike-sharing-with-db:latest
       links:
           - "mysql:mldb"
       depends_on:
           mysql:
               condition: service_healthy
   mysql:
       command: --init-file /data/application/init_ml_db.sql
       volumes:
           - ./init_ml_db.sql:/data/application/init_ml_db.sql
       container_name: mldb
       restart: always
       environment:
           MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
           MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
           MYSQL_DATABASE: ml_pipe_db
           MYSQL_TCP_PORT: ${MYSQL_CLIENT_PORT}
       image: mysql
       healthcheck:
           test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
           timeout: 20s
           retries: 10
       logging:
           driver: none